print("Hello, what is your name?")
name = input("What is your name?:")
print(f"Hello {name} and welcome to the story!")
print("")
print("")
animal = input("Pick a character: ")
location = input("Now pick a location:")
print("")
print(f"One day {animal} sprinted to a {location} to meet a friend")
friend = input("Who is their friend?")
print(f"{friend} and {animal} browsed through the {location} until they saw a..." )
eye = input("What did they see?")
print(f"The {eye} begged {friend} and {animal} to be taken home")
print(f"The 2 friends took the {eye} home, happy that they made a new friend")
print("")
print("")
print("THE END")